### PR TITLE
Autocomplete: Disabled and read-only not working as expected fix 

### LINKED ISSUE #213: Autocomplete: Disabled and ReadOnly functionality are not working as expected
The options that were selected could still be removed when using the Read Only option in multiselect mode.

Image

The same behavior was observed in disabled mode as well

https://github.com/user-attachments/assets/1dcecb53-08e0-4839-8d7a-dad498dc7c60

### PR DESCRIPTION
**Pull request by prashanthr6383**
### :page_facing_up: Summary of Changes

- Fixed click event issues for disabled and readonly states
- UI Fixes

### :thought_balloon: Type of Change

- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

[comment]: # 'How do you know the changes are safe to ship to production?'
[comment]: # 'How do you know the changes will function as expected in future releases?'

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [ ] My code is clean and readable
- [ ] I followed standard conventions
- [ ] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [ ] I have made Storybook changes including usage documentation (if applicable)
- [ ] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Work Item

Issue #213

### CODE REVIEW

**Comment by Kavin-Trimble** [comment]
In Dark Mode, no difference is observed visually on enabling read-only
image

Also, an inner border is seen in Mutiselect mode for the text input. Is that expected?
image

**Comment by prashanthr6383** [comment]
> In Dark Mode, no difference is observed visually on enabling read-only image
> 
> Also, an inner border is seen in Mutiselect mode for the text input. Is that expected? image

Since the Figma design for autocomplete in disabled and read-only states is unavailable, I referred to the input and chip components to implement this.

1. In Dark Mode, no difference is observed visually on enabling read-only ?
                              Typically read-only state usually does not have significant UI changes; it only restricts user interaction.
2.Also, an inner border is seen in Mutiselect mode for the text input. Is that expected? 
                            This behavior already exists and is not related to the changes in this PR.

**Comment by Kavin-Trimble** [comment]
> > In Dark Mode, no difference is observed visually on enabling read-only image
> > Also, an inner border is seen in Mutiselect mode for the text input. Is that expected? image
> 
> Since the Figma design for autocomplete in disabled and read-only states is unavailable, I referred to the input and chip components to implement this.
> 
> 1. In Dark Mode, no difference is observed visually on enabling read-only ?
>    Typically read-only state usually does not have significant UI changes; it only restricts user interaction.
>    2.Also, an inner border is seen in Mutiselect mode for the text input. Is that expected?
>    This behavior already exists and is not related to the changes in this PR.

**Regarding the comment:**

"In Dark Mode, no difference is observed visually on enabling read-only ?
Typically read-only state usually does not have significant UI changes; it only restricts user interaction."

@gabriel-piltzer-trimble, If this is fine, as @prashanthr6383 mentioned, this PR can be reviewed and merged. Testing completed from my end. If any changes are required, add your thoughts.

File: src/components/modus-wc-autocomplete/modus-wc-autocomplete.tsx [hunk 1]
```diff
@@ -256,6 +280,7 @@ export class ModusWcAutocomplete {
                 aria-label="Remove item button"
                 color="secondary"
                 onClick={() => this.handleChipRemove(item)}
+                disabled={this.disabled}
```
Comment (stuart-rimel) [inline src/components/modus-wc-autocomplete/modus-wc-autocomplete.tsx]: Should we also disable chips when the autocomplete is in a read only state?

**Review by stuart-rimel — COMMENTED** [review]
Changes seem correct with respect to issue #213. 

Just one question regarding chips

File: src/components/modus-wc-autocomplete/modus-wc-autocomplete.tsx (hunk 1 above)
Comment (prashanthr6383) [reply src/components/modus-wc-autocomplete/modus-wc-autocomplete.tsx]: > Should we also disable chips when the autocomplete is in a read only state?

Yes updated. handled in the function but good to have here.

**Review by stuart-rimel — APPROVED** [review]
