### PR TITLE
Fix Table cursor pointer display and inline editing bugs

### LINKED ISSUE #658: Table: Table row (tr) cursor is pointer even when not editable (or selectable)
### Prerequisites

- [x] I have [searched](https://github.com/trimble-oss/modus-wc-2.0/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-wc-2.0/blob/main/CONTRIBUTING.md)

### Describe the issue

Editable is false, so clicking the row does nothing. Visually, cursor style pointer indicates that it should do something:
Image

### Reduced test cases

Create a default table (e.g. [the storybook](https://trimble-oss.github.io/modus-wc-2.0/prod/?path=/docs/components-table--docs))
Note that editable is false
Hover over the rows (note that cursor style is pointer)
Click (or double click) row (nothing happens) (related - Is double click intuitive for edit? Is single click supposed to do something e.g. select row?)

I would expect only editable cells to show a pointer cursor (or selectable, if the whole row can be clicked to select)
Modus 1 supported single click anywhere on a row to select & single click an editable cell to edit (not sure whether those interfered with each other) but did not have any cursor style to indicate this (it used default)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding?

@trimble-oss/modus-wc

### What version of npm package are you using?

v1.0.0

### Priority

Low

### What product/project are you using Modus Web Components for?

WorksManager

### What is your team/division name?

CCFS-CS/Weka

### Are you willing to contribute?

Yes

### Are you using Modus Web Components in production?

_No response_

### LINKED ISSUE #714: Table: Last row of status not editable in table inline-editing
### Prerequisites

- [x] I have [searched](https://github.com/trimble-oss/modus-wc-2.0/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-wc-2.0/blob/main/CONTRIBUTING.md)

### Describe the issue

In the table inline-editing variant, the last row containing the status field cannot be edited, while all other rows can be edited by double-clicking.

**Steps to Reproduce**
1. Open the Table → inline-editing variant.
2. Double-click the Status cell in the first row → it enters edit mode.
3. Double-click the Status cell in the last row.

**Expected**
The Status cell in the last row should enter edit mode like the others.

**Actual**
The Status cell in the last row does not enter edit mode and remains uneditable.

### Reduced test cases

_No response_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding?

@trimble-oss/modus-wc

### What version of npm package are you using?

_No response_

### Priority

Medium

### What product/project are you using Modus Web Components for?

Modus

### What is your team/division name?

Modus

### Are you willing to contribute?

None

### Are you using Modus Web Components in production?

_No response_

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
### :page_facing_up: Summary of Changes
- Apply cursor pointer conditionally based on row selectable/editable state
- Fix activeEditorElement preventing edit mode on last row cells
### :thought_balloon: Type of Change

- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [x] Other

### :clipboard: Test Plan

[comment]: # 'How do you know the changes are safe to ship to production?'
[comment]: # 'How do you know the changes will function as expected in future releases?'

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [ ] My code is clean and readable
- [ ] I followed standard conventions
- [ ] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [ ] I have made Storybook changes including usage documentation (if applicable)
- [ ] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Work Item

Issue #658 #714

### CODE REVIEW

File: src/components/modus-wc-table/modus-wc-table.tsx [hunk 1]
```diff
@@ -883,13 +888,27 @@ export class ModusWcTable {
...
+                                  el.innerHTML = '';
+                                  if (
+                                    typeof cellNode !== 'string' &&
+                                    'tagName' in cellNode
+                                  ) {
+                                    el.appendChild(cellNode);
+                                  } else {
+                                    el.textContent = String(cellNode);
+                                  }
+                                }
```
[the remark this answers is not in the document]
Comment (ElishaSamPeterPrabhu) [reply src/components/modus-wc-table/modus-wc-table.tsx:924]: Addressed

File: src/components/modus-wc-table/modus-wc-table.scss [hunk 2]
```diff
@@ -201,7 +201,17 @@ modus-wc-table .modus-wc-overflow-x-auto {
...
 
-  tbody tr {
+  /* Cursor styles based on interactivity */
+  tbody tr.selectable {
+    cursor: pointer;
+  }
+
+  tbody tr.editable {
+    cursor: pointer;
+  }
```
Comment (prashanthr6383) [inline src/components/modus-wc-table/modus-wc-table.scss:209]: only interactive cells need to be cursor pointer not the rows

Comment (ElishaSamPeterPrabhu) [reply src/components/modus-wc-table/modus-wc-table.scss:209]: Addressed

File: src/components/modus-wc-table/modus-wc-table.scss [hunk 3]
```diff
@@ -201,17 +201,15 @@ modus-wc-table .modus-wc-overflow-x-auto {
...
+  /* Editable cells should show pointer cursor */
+  td.editable-cell {
     cursor: pointer;
   }
 
-  /* Editable cells should show pointer cursor */
-  td.editable-cell {
+  /* Selection column cells should show pointer cursor */
+  td.selection-column {
     cursor: pointer;
```
Comment (prashanthr6383) [inline src/components/modus-wc-table/modus-wc-table.scss]: Do we need this ? the checkbox already have cursor css

Comment (ElishaSamPeterPrabhu) [reply src/components/modus-wc-table/modus-wc-table.scss]: Addressed

**Comment by prashanthr6383** [comment]
Moving to Qa

**Review by prashanthr6383 — DISMISSED** [review]

**Comment by jewel-shajan** [comment]
@ElishaSamPeterPrabhu In tables where row selection is enabled, clicking a button inside row also selects the entire row.

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu In tables where row selection is enabled, clicking a button inside row also selects the entire row.

Addressed

**Review by Sunder005 — DISMISSED** [review]
Approved , moving to QA

**Comment by jewel-shajan** [comment]
@ElishaSamPeterPrabhu In the example story, remove the Button column. Also, in inline editing, the last cell of the Status column needs to be corrected.

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu In the example story, remove the Button column. Also, in inline editing, the last cell of the Status column needs to be corrected.

Addressed

**Comment by prashanthr6383** [comment]
@ElishaSamPeterPrabhu  Still the cursor pointer on non editable cell

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu Still the cursor pointer on non editable cell

Addressed

**Review by prashanthr6383 — APPROVED** [review]
