### PR TITLE
fix: adds auto-complete prop to autocomplete component

### LINKED ISSUE #761: Autocomplete: It should include the auto-complete prop
### Prerequisites

- [x] I have [searched](https://github.com/trimble-oss/modus-wc-2.0/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-wc-2.0/blob/main/CONTRIBUTING.md)

### Describe the issue

The Autocomplete component doesn't have the auto-complete prop like the other components.

It would be good to include the prop to prevent the browser's autofill.

Image

### Reduced test cases

_No response_

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge

### What is the issue regarding?

@trimble-oss/modus-wc-react

### What version of npm package are you using?

1.0.3

### Priority

High

### What product/project are you using Modus Web Components for?

Trimble Financial

### What is your team/division name?

AECO

### Are you willing to contribute?

None

### Are you using Modus Web Components in production?

_No response_

### PR DESCRIPTION
**Pull request by Kai-Richardson**
### :page_facing_up: Summary of Changes

Adds a prop `auto-complete` to the autocomplete component that forwards to the autocomplete prop on the inner text-input component.

It was missing from this component and needed to control autofill (which we don't want, as a consumer of this library).

### :thought_balloon: Type of Change

- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

Tested this locally. It's just adding the prop that exists on the other input components and forwarding it to the inner text-input.

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [x] My code is clean and readable
- [x] I followed standard conventions
- [ ] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [x] I have made documentation changes (if applicable)
- [x] I have made Storybook changes including usage documentation (if applicable)
- [x] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Work Item

Fixes #761

### CODE REVIEW

File: src/components/modus-wc-autocomplete/modus-wc-autocomplete-core.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { Fragment, h, JSX } from '@stencil/core';
 import { CloseSolidIcon } from '../../icons/close-solid.icon';
 import { SearchSolidIcon } from '../../icons/search-solid.icon';
 import {
+  AutocompleteTypes,
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-autocomplete/modus-wc-autocomplete-core.tsx:5]: The `AutocompleteTypes` in `src/components/types.ts` should be widened to support space-separated tokens lists per the [MDN spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/autocomplete). The `autocomplete` attribute accepts space-separated ordered tokens (e.g. `"shipping street-address"`), so the strict string literal union currently makes these valid values type errors. Developers can also pass any custom string value as per the [MDN spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/autocomplete).

**Review by ElishaSamPeterPrabhu — CHANGES_REQUESTED** [review]

File: src/components/modus-wc-autocomplete/modus-wc-autocomplete-core.tsx (hunk 1 above)
Comment (Kai-Richardson) [reply src/components/modus-wc-autocomplete/modus-wc-autocomplete-core.tsx:5]: This is a preexisting bug with every single input that accepts this prop to set the autocomplete property.

Accepting anything at all is surely better than nothing, and fixing the larger bug that it doesn't support space-separated tokens sounds like it'd be better done in a different PR.

Also, you say you can pass any string value per MDN, but **that's not true**. It's nowhere on the page. 

If you look at the *actual* spec it MUST be a single token/detail token or a space-separated list: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute

Comment (ElishaSamPeterPrabhu) [reply src/components/modus-wc-autocomplete/modus-wc-autocomplete-core.tsx:5]: Yeah, you’re right, we can’t pass just any string. I got confused with the `family-name` value, sorry about that. We’re introducing the `autocomplete` prop, and space-separated tokens should definitely be included through this. We can address this in the current PR or immediately after, so we can include it in the same release.

**Review by ElishaSamPeterPrabhu — APPROVED** [review]
Moving to QA @jewel-shajan @Kavin-Trimble

**Comment by jewel-shajan** [comment]
@Kai-Richardson Testing completed and ready to merge.
