### PR TITLE
Tooltip : Enable force open to show tooltip instead of hover

### LINKED ISSUE #585: Tooltip: force-open property is not working as expected.
### Prerequisites

- [x] I have [searched](https://github.com/trimble-oss/modus-wc-2.0/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-wc-2.0/blob/main/CONTRIBUTING.md)

### Describe the issue

When force-open is set to true, the tooltip should stay visible regardless of clicking outside or hovering, and when false, it should only appear on hover. Currently, this behavior is not working as expected.

### Reduced test cases

_No response_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding?

@trimble-oss/modus-wc

### What version of npm package are you using?

_No response_

### Priority

Medium

### What product/project are you using Modus Web Components for?

Modus

### What is your team/division name?

Modus

### Are you willing to contribute?

None

### Are you using Modus Web Components in production?

_No response_

### PR DESCRIPTION
**Pull request by prashanthr6383**
### :page_facing_up: Summary of Changes

- Enable force open to show tooltip instead of hover
- UI fixes - word break, content center alignment 

### :thought_balloon: Type of Change

- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

[comment]: # 'How do you know the changes are safe to ship to production?'
[comment]: # 'How do you know the changes will function as expected in future releases?'

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [x] My code is clean and readable
- [ ] I followed standard conventions
- [ ] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [ ] I have made Storybook changes including usage documentation (if applicable)
- [ ] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Work Item

Issue #585 #596

### CODE REVIEW

**Review by ElishaSamPeterPrabhu — CHANGES_REQUESTED** [review]
Our current approach: The tooltip is not dismissed when the Escape key is pressed after setting `forceOpen` to the tooltip.

- In this case, the tooltip is dismissed when Escape is pressed even after `forceOpen` is enabled.

- Additionally, once the tooltip is dismissed by pressing Escape, setting `forceOpen` again does not show the tooltip visually.

https://github.com/user-attachments/assets/0a9e94eb-bf79-41f9-8404-c3a1be45ad0c

**Comment by prashanthr6383** [comment]
> Our current approach: The tooltip is not dismissed when the Escape key is pressed after setting `forceOpen` to the tooltip.
> 
> * In this case, the tooltip is dismissed when Escape is pressed even after `forceOpen` is enabled.
> * Additionally, once the tooltip is dismissed by pressing Escape, setting `forceOpen` again does not show the tooltip visually.
> 
>  tooltip.mp4

updated

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 1]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
...
   }
 
+  @Watch('forceOpen')
+  handleForceOpenChange(newForceOpen: boolean) {
+    if (newForceOpen && !this.disabled && !this.escapeDismissed) {
+      this.showTooltip();
+    } else if (!newForceOpen) {
+      this.hideTooltip();
+    }
+  }
```
[the remark this answers is not in the document]
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: not required

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 2]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
...
+
   @Listen('mouseenter')
   handleMouseEnter() {
-    // Reset escape dismissal and set visibility state
-    this.escapeDismissed = false;
+    // If escapeDismissed is true, reset it on mouseenter
```
[the remark this answers is not in the document]
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: not required

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 3]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
...
   }
 
   @Listen('mouseleave')
   handleMouseLeave() {
-    // Clear visibility state
-    this.isVisible = false;
-    this.hideTooltip();
+    // Clear visibility state only if not forced open
+    if (!this.forceOpen) {
+      this.isVisible = false;
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: Since the `hideTooltip` function manages the visibility, there's no need to set it here.

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 4]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
...
+
   @Listen('mouseenter')
   handleMouseEnter() {
-    // Reset escape dismissal and set visibility state
-    this.escapeDismissed = false;
+    // If escapeDismissed is true, reset it on mouseenter
+    if (this.escapeDismissed) {
+      this.escapeDismissed = false;
+    }
     this.isVisible = true;
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: Since the `showTooltip` function manages the visibility, there's no need to set it here.

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 5]
```diff
@@ -68,8 +68,8 @@ export class ModusWcTooltip {
   elementKeyupHandler(event: KeyboardEvent): void {
     switch (event.code) {
       case 'Escape': {
-        // Escape only works when hovering (isVisible is true)
-        // This ensures when forceOpen is true, escape only works during hover
+        // Allow Escape to dismiss tooltip when it's visible
+        // When forceOpen is true, Escape should NOT dismiss it
         if (this.isVisible && !this.forceOpen) {
           this.escapeDismissed = true;
           this.isVisible = false;
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: Since the `hideTooltip` function manages the visibility, there's no need to set it here.

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 6]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
     }
   }
 
+  @Watch('forceOpen')
+  handleForceOpenChange(newForceOpen: boolean) {
+    if (newForceOpen && !this.disabled && !this.escapeDismissed) {
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: Can you clarify why we check if `escapeDismissed` is false when `forceOpen` is triggered?
As escapeDismissed won't have any effect unless the tooltip is visible

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 7]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
     }
   }
 
+  @Watch('forceOpen')
+  handleForceOpenChange(newForceOpen: boolean) {
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: can we just name it as `forceOpen` ?

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 8]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
...
+    if (newForceOpen && !this.disabled && !this.escapeDismissed) {
+      this.showTooltip();
+    } else if (!newForceOpen) {
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: Can this be just `else` ?

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx [hunk 9]
```diff
@@ -247,19 +247,32 @@ export class ModusWcTooltip {
...
+      this.hideTooltip();
+    }
+  }
+
   @Listen('mouseenter')
   handleMouseEnter() {
-    // Reset escape dismissal and set visibility state
-    this.escapeDismissed = false;
+    // If escapeDismissed is true, reset it on mouseenter
+    if (this.escapeDismissed) {
```
Comment (ElishaSamPeterPrabhu) [inline src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: Do we have a need to check `escapeDismissed` before setting it to false?

**Review by ElishaSamPeterPrabhu — CHANGES_REQUESTED** [review]

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 9 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: removed

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 8 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: no logic will change on setting any other to forceopen will  also fall on else part

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 7 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: okay updated

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 6 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: removed

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 5 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: removed

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 3 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: removed

File: src/components/modus-wc-tooltip/modus-wc-tooltip.tsx (hunk 4 above)
Comment (prashanthr6383) [reply src/components/modus-wc-tooltip/modus-wc-tooltip.tsx]: removed

**Review by ElishaSamPeterPrabhu — APPROVED** [review]

**Comment by ElishaSamPeterPrabhu** [comment]
@Kavin-Trimble Ready for testing

**Comment by Kavin-Trimble** [comment]
Testing completed, force open and overflow works as expected
